### ISSUE TITLE
Help on how to build for Windows

### ISSUE THREAD

**Issue by sd65** [avih/miniweb#10]
Hi,

This project will be used for education purposes and I need to build it for Windows. The thing is I don't know anything about this platform.
Would you be kind enough to provide information on how to build this project on Windows ?

Thanks !

**Comment by avih** [comment]
Hi,

I wouldn't recommend educating anyone with this project because the code is complex, hard to secure, with a lot of features disabled, and currently not maintained (I took someone else's project and only made small fixes/additions/modifications to make it useful, while disabling a lot of things).

Nevertheless, to build it on windows you'll need a mingw setup (most probably also possible with visual studio, but the project file is unmaintained). Simply go to the source directory and run `make` - same as on any other platform.

The easiest way to get a useful build environment on windows is probably using MSYS2 - https://www.msys2.org/ . Install it, ensure the mingw 32 or 64 compiler is installed (not sure if it's installed by default), and run `make` at the source dir.
