### ISSUE TITLE
HTTP Basic Authentication

### ISSUE THREAD

**Issue by TomaszGasior** [avih/miniweb#4]
It it possible to use HTTP Basic Authentication with this server? I see "basic auth" in project description but I am not able to find any information it in documentation and app built-in help.

I want to limit access to HTTP server to one password and username, for example: user:pass@domain. Server should block access to contents if username or password is incorrect. It is possible to do it with miniweb? I see it in source code but I don't know how to set username and password.

**Comment by avih** [comment]
To be honest I'm not entirely sure. It will certainly not work if it uses POST, because I completely disabled POST because it was insecure And you probably don't want to do auth with GET, because then the credentials+passwd could show up at the logs. And additionally it doesn't support HTTPS.

So even if it does work in some cases, I'd recommend against it with this server.

I forked the original project because I wanted a simple static server, and then I fixed some things like directory listing, big files support, and few more minor things, such that it's enough for my needs.

But other than those I'm not actively developing it and don't have plans to develop it further.

I don't mind trying to fix some notable bugs which people notice, but otherwise, it's pretty much what you see is what you get.

Sorry.
